CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE vendors (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE platforms (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), vendor_id UUID REFERENCES vendors(id), name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE sites (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE devices (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), hostname TEXT UNIQUE NOT NULL, vendor_id UUID REFERENCES vendors(id), platform_id UUID REFERENCES platforms(id), site_id UUID REFERENCES sites(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE interfaces (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), device_id UUID NOT NULL REFERENCES devices(id), name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE links (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), a_interface_id UUID REFERENCES interfaces(id), z_interface_id UUID REFERENCES interfaces(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE circuits (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), link_id UUID REFERENCES links(id), provider TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE intent_sets (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE intent_revisions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), intent_set_id UUID NOT NULL REFERENCES intent_sets(id), revision INT NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(intent_set_id, revision));
CREATE TABLE compiled_artifacts (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), intent_revision_id UUID REFERENCES intent_revisions(id), target_vendor TEXT NOT NULL, artifact TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE deployment_plans (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), intent_revision_id UUID REFERENCES intent_revisions(id), strategy TEXT NOT NULL, dry_run BOOLEAN NOT NULL DEFAULT true, idempotency_key TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE deployment_runs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), deployment_plan_id UUID REFERENCES deployment_plans(id), status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE deployment_targets (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), deployment_run_id UUID REFERENCES deployment_runs(id), device_id UUID REFERENCES devices(id), wave INT NOT NULL DEFAULT 1, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE config_snapshots (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), device_id UUID REFERENCES devices(id), content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE operational_snapshots (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), device_id UUID REFERENCES devices(id), content JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE drift_findings (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), device_id UUID REFERENCES devices(id), severity TEXT NOT NULL, finding JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE audit_events (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), actor TEXT NOT NULL, action TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), subject TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE permissions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE role_bindings (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID REFERENCES users(id), role_id UUID REFERENCES roles(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_devices_site ON devices(site_id);
CREATE INDEX idx_intent_revision_set ON intent_revisions(intent_set_id);
CREATE INDEX idx_deployment_targets_run ON deployment_targets(deployment_run_id);
